schema_version = "1.0.0"
id = "post_unwrap_cleaner"
version = "1.1.4"
name = "Post-Unwrap Cleaner"
tagline = "One-click UV cleanup after unwrap"
maintainer = "SMG Tools <support@smgtools.dev>"
type = "add-on"
website = "https://github.com/snmingi-dev/smg403/tree/main/projects/post-unwrap-cleaner"
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
copyright = ["2026 SMG Tools"]
